### PR TITLE
Upgrade plugin to kubesec v2

### PR DESCRIPTION
**Pull request by stefanprodan**
Use kubesec v2 API and allow overriding the kubesec URL with `export KUBESEC_URL=https://v2.kubesec.io/scan`

### CODE REVIEW

**Comment by stefanprodan** [comment]
@sublimino can you enable this repo in TravisCI please? Since it's open source you can use the free Travis.

**Comment by sublimino** [comment]
> @sublimino can you enable this repo in TravisCI please? Since it's open source you can use the free Travis.

Added to https://travis-ci.com/controlplaneio/kubesec-webhook/builds/114952900 as free Travis puts me in a redirect loop at login :man_shrugging: 

Think you'll need to force push to get the status check in this PR @stefanprodan

**Comment by stefanprodan** [comment]
Somehow is running in the free Travis https://travis-ci.org/controlplaneio/kubectl-kubesec/builds/543776716?utm_source=github_status&utm_medium=notification 😸

**Comment by stefanprodan** [comment]
This PR is ready for review now. To test it do:

```bash
make deploy
export PATH=$PATH:~/.kube/plugins/scan
kubectl scan deployment kube-dns -n kube-system 
```

**Pull request closed without merging**
